import { getDefaultModulesForArchetype } from "@foodorder/types";
import type { TemplateDefinition } from "./types";
import { unsplashImg } from "./image.helper";

export const BOOKING_TEMPLATES: TemplateDefinition[] = [
  {
    id: "barbershop",
    archetype: "booking",
    label: "Barbería",
    description: "Sistema de reservas para servicios de barbería profesional",
    categories: [
      { name: "Cortes de cabello", order: 1 },
      { name: "Afeitado", order: 2 },
      { name: "Tratamientos capilares", order: 3 },
      { name: "Paquetes", order: 4 },
    ],
    products: [
      // Cortes de cabello (5)
      {
        category: "Cortes de cabello",
        name: "Corte clásico",
        price: 12.0,
        durationMin: 20,
        description: "Corte básico tradicional",
        imageUrl: unsplashImg("barber haircut", 400, 300),
      },
      {
        category: "Cortes de cabello",
        name: "Corte con diseño",
        price: 18.0,
        durationMin: 30,
        description: "Diseño personalizado y líneas precisas",
        imageUrl: unsplashImg("barber fade haircut", 400, 300),
      },
      {
        category: "Cortes de cabello",
        name: "Fade corto",
        price: 15.0,
        durationMin: 25,
        description: "Fade moderno con líneas limpias",
        imageUrl: unsplashImg("fade haircut", 400, 300),
      },
      {
        category: "Cortes de cabello",
        name: "Corte texturizado",
        price: 20.0,
        durationMin: 35,
        description: "Corte con textura y volumen",
        imageUrl: unsplashImg("textured haircut men", 400, 300),
      },
      {
        category: "Cortes de cabello",
        name: "Línea de cabello",
        price: 10.0,
        durationMin: 15,
        description: "Limpieza de línea de cabello",
        imageUrl: unsplashImg("hairline trim", 400, 300),
      },
      // Afeitado (5)
      {
        category: "Afeitado",
        name: "Afeitado clásico",
        price: 8.0,
        durationMin: 15,
        description: "Afeitado tradicional con navaja",
        imageUrl: unsplashImg("barber shave", 400, 300),
      },
      {
        category: "Afeitado",
        name: "Afeitado con tratamiento",
        price: 15.0,
        durationMin: 25,
        description: "Afeitado + masaje y crema hidratante",
        imageUrl: unsplashImg("barber shaving cream", 400, 300),
      },
      {
        category: "Afeitado",
        name: "Afeitado + afeitar barba",
        price: 12.0,
        durationMin: 20,
        description: "Afeitado completo",
        imageUrl: unsplashImg("beard shave", 400, 300),
      },
      {
        category: "Afeitado",
        name: "Perfilado de barba",
        price: 6.0,
        durationMin: 10,
        description: "Solo perfilado y ajuste",
        imageUrl: unsplashImg("beard trim", 400, 300),
      },
      {
        category: "Afeitado",
        name: "Afeitado + corte",
        price: 20.0,
        durationMin: 40,
        description: "Paquete completo corte y afeitado",
        imageUrl: unsplashImg("barber grooming", 400, 300),
      },
      // Tratamientos capilares (3)
      {
        category: "Tratamientos capilares",
        name: "Hidratación capilar",
        price: 10.0,
        durationMin: 20,
        description: "Tratamiento profundo hidratante",
        imageUrl: unsplashImg("hair treatment", 400, 300),
      },
      {
        category: "Tratamientos capilares",
        name: "Tratamiento de barba",
        price: 12.0,
        durationMin: 25,
        description: "Aceite y acondicionador para barba",
        imageUrl: unsplashImg("beard treatment oil", 400, 300),
      },
      {
        category: "Tratamientos capilares",
        name: "Alisado capilar",
        price: 25.0,
        durationMin: 45,
        description: "Alisado temporal profesional",
        imageUrl: unsplashImg("hair straightening", 400, 300),
      },
      // Paquetes (2)
      {
        category: "Paquetes",
        name: "Pack semanal (4 servicios)",
        price: 40.0,
        description: "Válido por 7 días",
        imageUrl: unsplashImg("barber services", 400, 300),
      },
      {
        category: "Paquetes",
        name: "Membresía mensual",
        price: 80.0,
        description: "Acceso ilimitado a servicios",
        imageUrl: unsplashImg("barber membership", 400, 300),
      },
    ],
    defaultModules: {
      booking: true,
      product_modifiers: true,
      staff_management: true,
    },
  },
  {
    id: "spa-salon",
    archetype: "booking",
    label: "Spa y Salón de Belleza",
    description:
      "Reservas para servicios de spa, masajes y tratamientos de belleza",
    categories: [
      { name: "Masajes", order: 1 },
      { name: "Tratamientos faciales", order: 2 },
      { name: "Cuerpo y exfoliación", order: 3 },
      { name: "Cabello y color", order: 4 },
      { name: "Uñas", order: 5 },
    ],
    products: [
      // Masajes (5)
      {
        category: "Masajes",
        name: "Masaje relajante",
        price: 35.0,
        durationMin: 60,
        description: "Masaje sueco relajante",
        imageUrl: unsplashImg("spa massage", 400, 300),
      },
      {
        category: "Masajes",
        name: "Masaje terapéutico",
        price: 45.0,
        durationMin: 60,
        description: "Masaje profundo con técnicas terapéuticas",
        imageUrl: unsplashImg("therapeutic massage", 400, 300),
      },
      {
        category: "Masajes",
        name: "Masaje facial",
        price: 30.0,
        durationMin: 45,
        description: "Masaje facial relajante",
        imageUrl: unsplashImg("facial massage spa", 400, 300),
      },
      {
        category: "Masajes",
        name: "Masaje con piedras calientes",
        price: 50.0,
        durationMin: 75,
        description: "Masaje con piedras volcánicas",
        imageUrl: unsplashImg("hot stone massage", 400, 300),
      },
      {
        category: "Masajes",
        name: "Reflexología podal",
        price: 35.0,
        durationMin: 60,
        description: "Masaje terapéutico de pies",
        imageUrl: unsplashImg("foot reflexology", 400, 300),
      },
      // Tratamientos faciales (4)
      {
        category: "Tratamientos faciales",
        name: "Limpieza facial",
        price: 30.0,
        durationMin: 50,
        description: "Limpieza profunda con vapor",
        imageUrl: unsplashImg("facial cleanse treatment", 400, 300),
      },
      {
        category: "Tratamientos faciales",
        name: "Peeling químico",
        price: 40.0,
        durationMin: 60,
        description: "Peeling suave o profundo",
        imageUrl: unsplashImg("chemical peel", 400, 300),
      },
      {
        category: "Tratamientos faciales",
        name: "Facial hidratante",
        price: 35.0,
        durationMin: 55,
        description: "Tratamiento nutritivo e hidratante",
        imageUrl: unsplashImg("hydrating facial", 400, 300),
      },
      {
        category: "Tratamientos faciales",
        name: "Facial anti-edad",
        price: 50.0,
        durationMin: 70,
        description: "Tratamiento rejuvenecedor",
        imageUrl: unsplashImg("anti-aging facial", 400, 300),
      },
      // Cuerpo y exfoliación (4)
      {
        category: "Cuerpo y exfoliación",
        name: "Exfoliación corporal",
        price: 25.0,
        durationMin: 40,
        description: "Exfoliación con sal o azúcar",
        imageUrl: unsplashImg("body scrub exfoliation", 400, 300),
      },
      {
        category: "Cuerpo y exfoliación",
        name: "Envolvimiento corporal",
        price: 50.0,
        durationMin: 60,
        description: "Tratamiento de lodos y algas",
        imageUrl: unsplashImg("body wrap spa", 400, 300),
      },
      {
        category: "Cuerpo y exfoliación",
        name: "Depilación con cera",
        price: 20.0,
        durationMin: 30,
        description: "Depilación con cera tibia",
        imageUrl: unsplashImg("waxing service", 400, 300),
      },
      {
        category: "Cuerpo y exfoliación",
        name: "Hidratación corporal",
        price: 28.0,
        durationMin: 45,
        description: "Tratamiento hidratante intenso",
        imageUrl: unsplashImg("body hydration spa", 400, 300),
      },
      // Cabello y color (3)
      {
        category: "Cabello y color",
        name: "Corte y peinado",
        price: 25.0,
        durationMin: 45,
        description: "Corte profesional con estilo",
        imageUrl: unsplashImg("hair styling", 400, 300),
      },
      {
        category: "Cabello y color",
        name: "Coloración",
        price: 40.0,
        durationMin: 90,
        description: "Tinte profesional con técnicas modernas",
        imageUrl: unsplashImg("hair coloring", 400, 300),
      },
      {
        category: "Cabello y color",
        name: "Tratamiento capilar",
        price: 35.0,
        durationMin: 50,
        description: "Hidratación y recuperación del cabello",
        imageUrl: unsplashImg("hair treatment spa", 400, 300),
      },
      // Uñas (2)
      {
        category: "Uñas",
        name: "Manicura",
        price: 18.0,
        durationMin: 35,
        description: "Manicura clásica o spa",
        imageUrl: unsplashImg("manicure nail spa", 400, 300),
      },
      {
        category: "Uñas",
        name: "Pedicura",
        price: 22.0,
        durationMin: 45,
        description: "Pedicura spa relajante",
        imageUrl: unsplashImg("pedicure foot spa", 400, 300),
      },
    ],
    defaultModules: {
      booking: true,
      product_modifiers: true,
      staff_management: true,
    },
  },
  {
    id: "medical-clinic",
    archetype: "booking",
    label: "Clínica Médica",
    description: "Sistema de citas para consultas médicas y especialidades",
    categories: [
      { name: "Medicina general", order: 1 },
      { name: "Especialidades", order: 2 },
      { name: "Procedimientos", order: 3 },
      { name: "Controles", order: 4 },
    ],
    products: [
      // Medicina general (4)
      {
        category: "Medicina general",
        name: "Consulta de rutina",
        price: 35.0,
        durationMin: 30,
        description: "Consulta médica general",
        imageUrl: unsplashImg("doctor consultation", 400, 300),
      },
      {
        category: "Medicina general",
        name: "Primera consulta",
        price: 50.0,
        durationMin: 45,
        description: "Evaluación inicial completa",
        imageUrl: unsplashImg("medical consultation", 400, 300),
      },
      {
        category: "Medicina general",
        name: "Seguimiento",
        price: 30.0,
        durationMin: 25,
        description: "Control y seguimiento",
        imageUrl: unsplashImg("doctor followup", 400, 300),
      },
      {
        category: "Medicina general",
        name: "Vacunación",
        price: 20.0,
        durationMin: 15,
        description: "Aplicación de vacunas",
        imageUrl: unsplashImg("vaccination", 400, 300),
      },
      // Especialidades (5)
      {
        category: "Especialidades",
        name: "Cardiología",
        price: 60.0,
        durationMin: 40,
        description: "Consulta con cardiólogo",
        imageUrl: unsplashImg("cardiology doctor", 400, 300),
      },
      {
        category: "Especialidades",
        name: "Dermatología",
        price: 50.0,
        durationMin: 35,
        description: "Consulta dermatológica",
        imageUrl: unsplashImg("dermatology skin", 400, 300),
      },
      {
        category: "Especialidades",
        name: "Oftalmología",
        price: 45.0,
        durationMin: 35,
        description: "Examen oftalmológico",
        imageUrl: unsplashImg("eye examination", 400, 300),
      },
      {
        category: "Especialidades",
        name: "Odontología",
        price: 55.0,
        durationMin: 40,
        description: "Consulta dental",
        imageUrl: unsplashImg("dental checkup", 400, 300),
      },
      {
        category: "Especialidades",
        name: "Psicología",
        price: 50.0,
        durationMin: 50,
        description: "Sesión con psicólogo",
        imageUrl: unsplashImg("psychology session", 400, 300),
      },
      // Procedimientos (4)
      {
        category: "Procedimientos",
        name: "Extracción de sangre",
        price: 15.0,
        durationMin: 10,
        description: "Toma de muestra",
        imageUrl: unsplashImg("blood test", 400, 300),
      },
      {
        category: "Procedimientos",
        name: "Ecografía",
        price: 80.0,
        durationMin: 30,
        description: "Ultrasonido diagnóstico",
        imageUrl: unsplashImg("ultrasound", 400, 300),
      },
      {
        category: "Procedimientos",
        name: "Electrocardiograma",
        price: 40.0,
        durationMin: 20,
        description: "ECG completo",
        imageUrl: unsplashImg("ecg test", 400, 300),
      },
      {
        category: "Procedimientos",
        name: "Prueba de esfuerzo",
        price: 100.0,
        durationMin: 45,
        description: "Test cardiopulmonar",
        imageUrl: unsplashImg("stress test", 400, 300),
      },
      // Controles (2)
      {
        category: "Controles",
        name: "Control de presión",
        price: 10.0,
        durationMin: 5,
        description: "Medición de presión arterial",
        imageUrl: unsplashImg("blood pressure check", 400, 300),
      },
      {
        category: "Controles",
        name: "Control de glucosa",
        price: 12.0,
        durationMin: 5,
        description: "Medición de glucosa",
        imageUrl: unsplashImg("glucose test", 400, 300),
      },
    ],
    defaultModules: {
      booking: true,
      staff_management: true,
    },
  },
  {
    id: "booking-en-blanco",
    archetype: "booking",
    label: "Reservas en Blanco",
    description:
      "Template vacío para crear un sistema de reservas personalizado",
    categories: [{ name: "Servicios", order: 1 }],
    products: [],
    defaultModules: getDefaultModulesForArchetype("booking"),
  },
];
