import { getDefaultModulesForArchetype } from "@foodorder/types";
import type { TemplateDefinition } from "./types";
import { unsplashImg } from "./image.helper";

export const FOOD_TEMPLATES: TemplateDefinition[] = [
  {
    id: "restaurant-qr",
    archetype: "food",
    label: "Restaurante QR",
    description: "Carta digital completa con pedidos por mesa y delivery",
    categories: [
      { name: "Entradas", order: 1 },
      { name: "Platos principales", order: 2 },
      { name: "Pastas", order: 3 },
      { name: "Ensaladas", order: 4 },
      { name: "Postres", order: 5 },
      { name: "Bebidas", order: 6 },
    ],
    products: [
      // Entradas
      {
        category: "Entradas",
        name: "Tequeños (6u)",
        price: 4.5,
        description: "Bocaditos de queso fritos crujientes",
        imageUrl: unsplashImg("tequeños cheese fried", 400, 300),
      },
      {
        category: "Entradas",
        name: "Empanadas mixtas",
        price: 5.0,
        description: "3 unidades a elección - carne, queso o verdura",
        imageUrl: unsplashImg("empanadas food", 400, 300),
      },
      {
        category: "Entradas",
        name: "Ceviche",
        price: 8.5,
        description: "Ceviche fresco con limón y cilantro",
        imageUrl: unsplashImg("ceviche", 400, 300),
      },
      {
        category: "Entradas",
        name: "Camarones al ajillo",
        price: 9.5,
        description: "Camarones frescos salteados con ajo",
        imageUrl: unsplashImg("shrimp garlic", 400, 300),
      },
      {
        category: "Entradas",
        name: "Tabla de quesos y jamones",
        price: 12.0,
        description: "Selección de quesos y jamones premium",
        imageUrl: unsplashImg("cheese board charcuterie", 400, 300),
      },
      // Platos principales
      {
        category: "Platos principales",
        name: "Pabellón criollo",
        price: 12.0,
        description: "Carne mechada, arroz, frijoles y tajadas",
        imageUrl: unsplashImg("traditional meat rice plate", 400, 300),
      },
      {
        category: "Platos principales",
        name: "Parrilla mixta",
        price: 18.0,
        description: "Para 2 personas - carnes variadas a la parrilla",
        imageUrl: unsplashImg("grilled meat platter", 400, 300),
      },
      {
        category: "Platos principales",
        name: "Filete a la pimienta",
        price: 15.5,
        description: "Filete jugoso con salsa de pimienta",
        imageUrl: unsplashImg("steak peppercorn sauce", 400, 300),
      },
      {
        category: "Platos principales",
        name: "Costillas BBQ",
        price: 14.0,
        description: "Costillas tiernas con salsa BBQ casera",
        imageUrl: unsplashImg("bbq ribs", 400, 300),
      },
      {
        category: "Platos principales",
        name: "Pollo a la mostaza",
        price: 11.0,
        description: "Pechuga de pollo con salsa de mostaza Dijon",
        imageUrl: unsplashImg("chicken mustard sauce", 400, 300),
      },
      {
        category: "Platos principales",
        name: "Salmón a la mantequilla",
        price: 16.5,
        description: "Filete de salmón fresco con limón y alcaparras",
        imageUrl: unsplashImg("salmon butter lemon", 400, 300),
      },
      // Pastas
      {
        category: "Pastas",
        name: "Spaghetti a la carbonara",
        price: 10.0,
        description: "Pasta fresca con huevo, queso y panceta",
        imageUrl: unsplashImg("spaghetti carbonara", 400, 300),
      },
      {
        category: "Pastas",
        name: "Fettuccine Alfredo",
        price: 9.5,
        description: "Pasta cremosa con salsa Alfredo auténtica",
        imageUrl: unsplashImg("fettuccine alfredo", 400, 300),
      },
      {
        category: "Pastas",
        name: "Penne al ragù",
        price: 10.5,
        description: "Pasta con ragù tradicional italiano",
        imageUrl: unsplashImg("penne bolognese", 400, 300),
      },
      {
        category: "Pastas",
        name: "Lasaña de carne",
        price: 11.0,
        description: "Capas de pasta, carne y queso gratinado",
        imageUrl: unsplashImg("lasagna meat", 400, 300),
      },
      // Ensaladas
      {
        category: "Ensaladas",
        name: "Ensalada César",
        price: 8.0,
        description: "Lechuga romana, queso parmesano y aderezo César",
        imageUrl: unsplashImg("caesar salad", 400, 300),
      },
      {
        category: "Ensaladas",
        name: "Ensalada Griega",
        price: 7.5,
        description: "Tomate, pepino, aceitunas y queso feta",
        imageUrl: unsplashImg("greek salad", 400, 300),
      },
      {
        category: "Ensaladas",
        name: "Ensalada de remolacha",
        price: 7.0,
        description: "Remolacha fresca con queso de cabra",
        imageUrl: unsplashImg("beet salad goat cheese", 400, 300),
      },
      // Postres
      {
        category: "Postres",
        name: "Quesillo",
        price: 4.0,
        description: "Flan tradicional con dulce de leche",
        imageUrl: unsplashImg("flan caramel", 400, 300),
      },
      {
        category: "Postres",
        name: "Tiramisú",
        price: 5.5,
        description: "Postre italiano con mascarpone y café",
        imageUrl: unsplashImg("tiramisu", 400, 300),
      },
      {
        category: "Postres",
        name: "Brownie de chocolate",
        price: 4.5,
        description: "Brownie húmedo servido con helado de vainilla",
        imageUrl: unsplashImg("chocolate brownie ice cream", 400, 300),
      },
      {
        category: "Postres",
        name: "Cheesecake",
        price: 5.0,
        description: "Cheesecake de frutos rojos",
        imageUrl: unsplashImg("cheesecake berries", 400, 300),
      },
      // Bebidas
      {
        category: "Bebidas",
        name: "Refresco 350ml",
        price: 1.8,
        description: "Refrescos variados sin azúcar disponibles",
        imageUrl: unsplashImg("soda drink cold", 400, 300),
      },
      {
        category: "Bebidas",
        name: "Jugo natural",
        price: 3.0,
        description: "Parchita, mango, lechosa o naranja recién exprimido",
        imageUrl: unsplashImg("fresh juice orange", 400, 300),
      },
      {
        category: "Bebidas",
        name: "Agua con gas",
        price: 2.0,
        description: "Agua mineral con gas premium",
        imageUrl: unsplashImg("sparkling water", 400, 300),
      },
      {
        category: "Bebidas",
        name: "Vino tinto",
        price: 8.0,
        description: "Vino tinto reserva seleccionado",
        imageUrl: unsplashImg("red wine glass", 400, 300),
      },
    ],
    defaultModules: {
      kitchen_kds: true,
      delivery_zones: true,
      scheduled_orders: true,
      product_modifiers: true,
      coupons_discounts: true,
    },
  },
  {
    id: "pizzeria",
    archetype: "food",
    label: "Pizzería",
    description: "Variantes de tamaño, toppings extras y combos especiales",
    categories: [
      { name: "Pizzas clásicas", order: 1 },
      { name: "Pizzas especiales", order: 2 },
      { name: "Acompañamientos", order: 3 },
      { name: "Bebidas", order: 4 },
      { name: "Postres", order: 5 },
    ],
    products: [
      // Pizzas clásicas
      {
        category: "Pizzas clásicas",
        name: "Margherita",
        price: 9.0,
        description: "Tomate, mozzarella fresca, albahaca",
        imageUrl: unsplashImg("margherita pizza", 400, 300),
      },
      {
        category: "Pizzas clásicas",
        name: "Pepperoni",
        price: 11.0,
        description: "Pepperoni y mozzarella extra fundida",
        imageUrl: unsplashImg("pepperoni pizza", 400, 300),
      },
      {
        category: "Pizzas clásicas",
        name: "Italiana",
        price: 10.0,
        description: "Jamón, champiñones y aceitunas",
        imageUrl: unsplashImg("italian pizza", 400, 300),
      },
      {
        category: "Pizzas clásicas",
        name: "Salsa blanca",
        price: 10.5,
        description: "Crema, jamón y champiñones",
        imageUrl: unsplashImg("white sauce pizza", 400, 300),
      },
      // Pizzas especiales
      {
        category: "Pizzas especiales",
        name: "Cuatro quesos",
        price: 13.0,
        description: "Mozzarella, queso azul, queso de cabra y parmesano",
        imageUrl: unsplashImg("four cheese pizza", 400, 300),
      },
      {
        category: "Pizzas especiales",
        name: "Hawaiana",
        price: 11.5,
        description: "Jamón ahumado y piña tropical",
        imageUrl: unsplashImg("hawaiian pizza pineapple", 400, 300),
      },
      {
        category: "Pizzas especiales",
        name: "BBQ Carne",
        price: 12.5,
        description: "Carne molida, bacon y salsa BBQ",
        imageUrl: unsplashImg("bbq meat pizza", 400, 300),
      },
      {
        category: "Pizzas especiales",
        name: "Vegetariana",
        price: 10.0,
        description: "Champiñones, pimiento, tomate y cebolla",
        imageUrl: unsplashImg("vegetarian pizza", 400, 300),
      },
      {
        category: "Pizzas especiales",
        name: "Mariscos",
        price: 14.0,
        description: "Camarones, mejillones y calamares frescos",
        imageUrl: unsplashImg("seafood pizza", 400, 300),
      },
      // Acompañamientos
      {
        category: "Acompañamientos",
        name: "Palitos de ajo",
        price: 4.0,
        description: "Palitos crujientes con ajo y hierbas",
        imageUrl: unsplashImg("garlic bread sticks", 400, 300),
      },
      {
        category: "Acompañamientos",
        name: "Alitas BBQ (6u)",
        price: 6.5,
        description: "Alitas tiernas con salsa BBQ",
        imageUrl: unsplashImg("bbq wings", 400, 300),
      },
      {
        category: "Acompañamientos",
        name: "Tabla de entrada",
        price: 12.0,
        description: "Tequeños, alitas y palitos de queso",
        imageUrl: unsplashImg("appetizer platter", 400, 300),
      },
      // Bebidas
      {
        category: "Bebidas",
        name: "Refresco 1.5L",
        price: 4.0,
        description: "Refresco frío para compartir",
        imageUrl: unsplashImg("soda bottle cold", 400, 300),
      },
      {
        category: "Bebidas",
        name: "Cerveza 355ml",
        price: 3.5,
        description: "Cerveza fría artesanal o comercial",
        imageUrl: unsplashImg("beer bottle cold", 400, 300),
      },
      {
        category: "Bebidas",
        name: "Gaseosa sin azúcar",
        price: 2.5,
        description: "Refrescos diet o zero azúcar",
        imageUrl: unsplashImg("diet soda", 400, 300),
      },
      // Postres
      {
        category: "Postres",
        name: "Brownie de chocolate",
        price: 4.5,
        description: "Brownie caliente con helado",
        imageUrl: unsplashImg("chocolate brownie", 400, 300),
      },
      {
        category: "Postres",
        name: "Tiramisú",
        price: 5.0,
        description: "Postre italiano tradicional",
        imageUrl: unsplashImg("tiramisu", 400, 300),
      },
      {
        category: "Postres",
        name: "Helado (2 bolas)",
        price: 3.5,
        description: "Helado artesanal variados sabores",
        imageUrl: unsplashImg("ice cream", 400, 300),
      },
      {
        category: "Postres",
        name: "Cheesecake",
        price: 5.0,
        description: "Cheesecake de arándanos",
        imageUrl: unsplashImg("cheesecake", 400, 300),
      },
    ],
    defaultModules: {
      kitchen_kds: true,
      delivery_zones: true,
      product_variants: true,
      product_modifiers: true,
      coupons_discounts: true,
    },
  },
  {
    id: "cafeteria",
    archetype: "food",
    label: "Cafetería & Snacks",
    description: "Bebidas calientes, desayunos rápidos y meriendas",
    categories: [
      { name: "Café", order: 1 },
      { name: "Desayunos", order: 2 },
      { name: "Pastelería", order: 3 },
      { name: "Snacks", order: 4 },
      { name: "Otras bebidas", order: 5 },
    ],
    products: [
      // Café
      {
        category: "Café",
        name: "Espresso",
        price: 1.5,
        description: "Café espresso intenso",
        imageUrl: unsplashImg("espresso coffee", 400, 300),
      },
      {
        category: "Café",
        name: "Cappuccino",
        price: 2.5,
        description: "Espresso con leche espumada y canela",
        imageUrl: unsplashImg("cappuccino latte", 400, 300),
      },
      {
        category: "Café",
        name: "Latte",
        price: 2.8,
        description: "Café con leche cremoso",
        imageUrl: unsplashImg("coffee latte", 400, 300),
      },
      {
        category: "Café",
        name: "Americano",
        price: 2.0,
        description: "Espresso largo con agua caliente",
        imageUrl: unsplashImg("american coffee", 400, 300),
      },
      {
        category: "Café",
        name: "Cortadito",
        price: 1.8,
        description: "Café con poco de leche condensada",
        imageUrl: unsplashImg("cortadito coffee", 400, 300),
      },
      // Desayunos
      {
        category: "Desayunos",
        name: "Tequeños y café",
        price: 4.5,
        description: "Tequeños frescos con café",
        imageUrl: unsplashImg("cheese pastry breakfast", 400, 300),
      },
      {
        category: "Desayunos",
        name: "Sandwich jamón y queso",
        price: 4.0,
        description: "Pan tostado con jamón y queso fundido",
        imageUrl: unsplashImg("ham cheese sandwich", 400, 300),
      },
      {
        category: "Desayunos",
        name: "Arepa rellena",
        price: 3.5,
        description: "Arepa con queso y jamón",
        imageUrl: unsplashImg("arepa cheese ham", 400, 300),
      },
      {
        category: "Desayunos",
        name: "Huevos con jamón",
        price: 4.0,
        description: "Huevos fritos con jamón y pan tostado",
        imageUrl: unsplashImg("eggs ham breakfast", 400, 300),
      },
      {
        category: "Desayunos",
        name: "Waffles",
        price: 5.5,
        description: "Waffles belgas con sirope y fresas",
        imageUrl: unsplashImg("waffles berries", 400, 300),
      },
      // Pastelería
      {
        category: "Pastelería",
        name: "Croissant",
        price: 2.0,
        description: "Croissant mantequilla francés",
        imageUrl: unsplashImg("croissant pastry", 400, 300),
      },
      {
        category: "Pastelería",
        name: "Torta del día",
        price: 3.5,
        description: "Surtido de tartas variadas",
        imageUrl: unsplashImg("cake pastry", 400, 300),
      },
      {
        category: "Pastelería",
        name: "Donas glaseadas",
        price: 2.5,
        description: "Donas rellenas de crema o mermelada",
        imageUrl: unsplashImg("donuts glazed", 400, 300),
      },
      {
        category: "Pastelería",
        name: "Muffin de arándanos",
        price: 3.0,
        description: "Muffin esponjoso con arándanos frescos",
        imageUrl: unsplashImg("blueberry muffin", 400, 300),
      },
      {
        category: "Pastelería",
        name: "Tarta de queso",
        price: 4.0,
        description: "Cheesecake tradicional",
        imageUrl: unsplashImg("cheesecake slice", 400, 300),
      },
      // Snacks
      {
        category: "Snacks",
        name: "Papas fritas",
        price: 2.0,
        description: "Papas fritas crujientes saladas",
        imageUrl: unsplashImg("french fries", 400, 300),
      },
      {
        category: "Snacks",
        name: "Popcorn de queso",
        price: 2.5,
        description: "Popcorn casero con queso",
        imageUrl: unsplashImg("popcorn cheese", 400, 300),
      },
      {
        category: "Snacks",
        name: "Galletas de avena",
        price: 1.5,
        description: "Galletas caseras de avena",
        imageUrl: unsplashImg("oatmeal cookies", 400, 300),
      },
      {
        category: "Snacks",
        name: "Almendras tostadas",
        price: 3.0,
        description: "Almendras con sal",
        imageUrl: unsplashImg("roasted almonds", 400, 300),
      },
      // Otras bebidas
      {
        category: "Otras bebidas",
        name: "Jugo natural",
        price: 3.0,
        description: "Parchita, mango o lechosa recién exprimido",
        imageUrl: unsplashImg("fresh juice", 400, 300),
      },
      {
        category: "Otras bebidas",
        name: "Batido de frutas",
        price: 3.5,
        description: "Batido con plátano y fresas",
        imageUrl: unsplashImg("smoothie berry", 400, 300),
      },
      {
        category: "Otras bebidas",
        name: "Chocolate caliente",
        price: 2.5,
        description: "Chocolate cremoso con leche",
        imageUrl: unsplashImg("hot chocolate", 400, 300),
      },
      {
        category: "Otras bebidas",
        name: "Té helado",
        price: 2.0,
        description: "Té frío con limón y hielo",
        imageUrl: unsplashImg("iced tea lemon", 400, 300),
      },
    ],
    defaultModules: {
      scheduled_orders: true,
      product_modifiers: true,
    },
  },
  {
    id: "food-en-blanco",
    archetype: "food",
    label: "Food en blanco",
    description: "Template vacío para personalizar el catálogo desde cero",
    categories: [],
    products: [],
    defaultModules: getDefaultModulesForArchetype("food"),
  },
];
