import { getDefaultModulesForArchetype } from "@foodorder/types";
import type { TemplateDefinition } from "./types";
import { unsplashImg } from "./image.helper";

export const RETAIL_TEMPLATES: TemplateDefinition[] = [
  {
    id: "clothing-store",
    archetype: "retail",
    label: "Tienda de Ropa",
    description: "Catálogo completo de prendas con tallas, colores y variantes",
    categories: [
      { name: "Camisetas", order: 1 },
      { name: "Pantalones", order: 2 },
      { name: "Chaquetas", order: 3 },
      { name: "Vestidos", order: 4 },
      { name: "Accesorios", order: 5 },
    ],
    products: [
      // Camisetas (7)
      {
        category: "Camisetas",
        name: "Camiseta básica blanca",
        price: 12.0,
        description: "Algodón 100%, disponible en todos los colores",
        imageUrl: unsplashImg("white cotton t-shirt", 400, 300),
      },
      {
        category: "Camisetas",
        name: "Camiseta premium",
        price: 25.0,
        description: "Algodón orgánico, acabado superior",
        imageUrl: unsplashImg("organic cotton t-shirt", 400, 300),
      },
      {
        category: "Camisetas",
        name: "Camiseta estampada",
        price: 15.0,
        description: "Diseños exclusivos y modernos",
        imageUrl: unsplashImg("graphic t-shirt", 400, 300),
      },
      {
        category: "Camisetas",
        name: "Camiseta slim fit",
        price: 18.0,
        description: "Ajuste moderno y cómodo",
        imageUrl: unsplashImg("slim fit t-shirt", 400, 300),
      },
      {
        category: "Camisetas",
        name: "Camiseta oversized",
        price: 16.0,
        description: "Corte amplio y relajado",
        imageUrl: unsplashImg("oversized t-shirt", 400, 300),
      },
      {
        category: "Camisetas",
        name: "Camiseta tipo polo",
        price: 22.0,
        description: "Elegante para casual o trabajo",
        imageUrl: unsplashImg("polo shirt", 400, 300),
      },
      {
        category: "Camisetas",
        name: "Camiseta sin mangas",
        price: 11.0,
        description: "Tank top básico para verano",
        imageUrl: unsplashImg("sleeveless tank top", 400, 300),
      },
      // Pantalones (7)
      {
        category: "Pantalones",
        name: "Jeans clásico",
        price: 45.0,
        description: "Corte recto, azul oscuro durable",
        imageUrl: unsplashImg("classic blue jeans", 400, 300),
      },
      {
        category: "Pantalones",
        name: "Jeans skinny",
        price: 42.0,
        description: "Ajuste ceñido y moderno",
        imageUrl: unsplashImg("skinny jeans", 400, 300),
      },
      {
        category: "Pantalones",
        name: "Jeans roto",
        price: 48.0,
        description: "Estilo urbano con roturas",
        imageUrl: unsplashImg("ripped jeans", 400, 300),
      },
      {
        category: "Pantalones",
        name: "Pantalón chino",
        price: 35.0,
        description: "Cómodo y versátil para cualquier ocasión",
        imageUrl: unsplashImg("khaki chino pants", 400, 300),
      },
      {
        category: "Pantalones",
        name: "Pantalón negro formal",
        price: 50.0,
        description: "Perfecto para trabajo y eventos",
        imageUrl: unsplashImg("black formal pants", 400, 300),
      },
      {
        category: "Pantalones",
        name: "Shorts denim",
        price: 28.0,
        description: "Shorts cortos de denim",
        imageUrl: unsplashImg("denim shorts", 400, 300),
      },
      {
        category: "Pantalones",
        name: "Leggings deportivos",
        price: 32.0,
        description: "Material elástico y cómodo",
        imageUrl: unsplashImg("sports leggings", 400, 300),
      },
      // Chaquetas (5)
      {
        category: "Chaquetas",
        name: "Chaqueta denim",
        price: 65.0,
        description: "Chaqueta clásica de denim",
        imageUrl: unsplashImg("denim jacket", 400, 300),
      },
      {
        category: "Chaquetas",
        name: "Chaqueta de cuero",
        price: 120.0,
        description: "Cuero genuino resistente",
        imageUrl: unsplashImg("leather jacket", 400, 300),
      },
      {
        category: "Chaquetas",
        name: "Chaqueta bomber",
        price: 55.0,
        description: "Estilo urbano y deportivo",
        imageUrl: unsplashImg("bomber jacket", 400, 300),
      },
      {
        category: "Chaquetas",
        name: "Blazer formal",
        price: 85.0,
        description: "Perfecto para la oficina",
        imageUrl: unsplashImg("blazer formal", 400, 300),
      },
      {
        category: "Chaquetas",
        name: "Sudadera con cierre",
        price: 40.0,
        description: "Cómoda y abrigada",
        imageUrl: unsplashImg("zip hoodie", 400, 300),
      },
      // Vestidos (4)
      {
        category: "Vestidos",
        name: "Vestido casual",
        price: 45.0,
        description: "Perfecto para el día a día",
        imageUrl: unsplashImg("casual dress", 400, 300),
      },
      {
        category: "Vestidos",
        name: "Vestido de fiesta",
        price: 85.0,
        description: "Elegante para eventos especiales",
        imageUrl: unsplashImg("party dress evening", 400, 300),
      },
      {
        category: "Vestidos",
        name: "Vestido floral",
        price: 50.0,
        description: "Estampado floral fresco",
        imageUrl: unsplashImg("floral dress", 400, 300),
      },
      {
        category: "Vestidos",
        name: "Vestido maxi",
        price: 60.0,
        description: "Largo elegante y cómodo",
        imageUrl: unsplashImg("maxi dress long", 400, 300),
      },
      // Accesorios (2)
      {
        category: "Accesorios",
        name: "Cinturón de cuero",
        price: 18.0,
        description: "Cinturón clásico de cuero genuino",
        imageUrl: unsplashImg("leather belt", 400, 300),
      },
      {
        category: "Accesorios",
        name: "Gorra y bufanda",
        price: 22.0,
        description: "Set de invierno abrigado",
        imageUrl: unsplashImg("winter hat scarf", 400, 300),
      },
    ],
    defaultModules: {
      product_variants: true,
      product_modifiers: true,
      inventory_tracking: true,
      coupons_discounts: true,
    },
  },
  {
    id: "hardware-store",
    archetype: "retail",
    label: "Ferretería",
    description: "Herramientas, materiales de construcción y equipos",
    categories: [
      { name: "Herramientas manuales", order: 1 },
      { name: "Electricidad", order: 2 },
      { name: "Plomería", order: 3 },
      { name: "Pintura y acabados", order: 4 },
      { name: "Seguridad", order: 5 },
      { name: "Equipos", order: 6 },
    ],
    products: [
      // Herramientas manuales (7)
      {
        category: "Herramientas manuales",
        name: "Martillo 2lb",
        price: 15.0,
        description: "Martillo de clavo estándar",
        imageUrl: unsplashImg("hammer tool", 400, 300),
      },
      {
        category: "Herramientas manuales",
        name: "Destornilladores set",
        price: 12.0,
        description: "Set de 6 destornilladores",
        imageUrl: unsplashImg("screwdriver set", 400, 300),
      },
      {
        category: "Herramientas manuales",
        name: "Llave inglesa",
        price: 10.0,
        description: 'Llave ajustable 8"',
        imageUrl: unsplashImg("adjustable wrench", 400, 300),
      },
      {
        category: "Herramientas manuales",
        name: "Alicate",
        price: 8.0,
        description: "Alicate combinado",
        imageUrl: unsplashImg("pliers tool", 400, 300),
      },
      {
        category: "Herramientas manuales",
        name: "Sierra de mano",
        price: 18.0,
        description: "Sierra para madera",
        imageUrl: unsplashImg("hand saw", 400, 300),
      },
      {
        category: "Herramientas manuales",
        name: "Nivel de burbuja",
        price: 12.0,
        description: 'Nivel de 24"',
        imageUrl: unsplashImg("spirit level", 400, 300),
      },
      {
        category: "Herramientas manuales",
        name: "Cinta métrica",
        price: 8.0,
        description: "Cinta de 25 metros",
        imageUrl: unsplashImg("measuring tape", 400, 300),
      },
      // Electricidad (6)
      {
        category: "Electricidad",
        name: "Cable eléctrico",
        price: 15.0,
        description: "Cable 10 metros 14AWG",
        imageUrl: unsplashImg("electrical cable", 400, 300),
      },
      {
        category: "Electricidad",
        name: "Interruptor de luz",
        price: 3.0,
        description: "Interruptor básico estándar",
        imageUrl: unsplashImg("light switch", 400, 300),
      },
      {
        category: "Electricidad",
        name: "Enchufe doble",
        price: 5.0,
        description: "Enchufe de pared",
        imageUrl: unsplashImg("electrical outlet", 400, 300),
      },
      {
        category: "Electricidad",
        name: "Bombilla LED",
        price: 4.5,
        description: "Bombilla E27 12W",
        imageUrl: unsplashImg("led bulb", 400, 300),
      },
      {
        category: "Electricidad",
        name: "Tubo fluorescente",
        price: 8.0,
        description: "Tubo 40W 1.2m",
        imageUrl: unsplashImg("fluorescent tube", 400, 300),
      },
      {
        category: "Electricidad",
        name: "Caja de fusibles",
        price: 25.0,
        description: "Panel de distribución 8 circuitos",
        imageUrl: unsplashImg("electrical panel", 400, 300),
      },
      // Plomería (6)
      {
        category: "Plomería",
        name: 'Caño PVC 1"',
        price: 6.0,
        description: "Caño de 3 metros",
        imageUrl: unsplashImg("pvc pipe", 400, 300),
      },
      {
        category: "Plomería",
        name: "Codo PVC 90°",
        price: 1.5,
        description: 'Codo de 1"',
        imageUrl: unsplashImg("pvc elbow fitting", 400, 300),
      },
      {
        category: "Plomería",
        name: "Grifo de agua",
        price: 22.0,
        description: "Grifo de latón cromado",
        imageUrl: unsplashImg("water faucet tap", 400, 300),
      },
      {
        category: "Plomería",
        name: "Válvula de paso",
        price: 12.0,
        description: 'Válvula de bola 1"',
        imageUrl: unsplashImg("ball valve", 400, 300),
      },
      {
        category: "Plomería",
        name: "Sellante plomero",
        price: 5.0,
        description: "Cinta de teflón 10m",
        imageUrl: unsplashImg("plumbers tape", 400, 300),
      },
      {
        category: "Plomería",
        name: "Bomba sumergible",
        price: 65.0,
        description: "Bomba 1/2HP",
        imageUrl: unsplashImg("water pump", 400, 300),
      },
      // Pintura y acabados (7)
      {
        category: "Pintura y acabados",
        name: "Pintura blanca",
        price: 18.0,
        description: "Pintura látex 1 galón",
        imageUrl: unsplashImg("white paint bucket", 400, 300),
      },
      {
        category: "Pintura y acabados",
        name: "Pintura de aceite",
        price: 25.0,
        description: "Pintura óleo 1 galón",
        imageUrl: unsplashImg("oil paint", 400, 300),
      },
      {
        category: "Pintura y acabados",
        name: "Pincel",
        price: 4.0,
        description: 'Pincel 2"',
        imageUrl: unsplashImg("paint brush", 400, 300),
      },
      {
        category: "Pintura y acabados",
        name: "Rodillo",
        price: 5.0,
        description: 'Rodillo de espuma 9"',
        imageUrl: unsplashImg("paint roller", 400, 300),
      },
      {
        category: "Pintura y acabados",
        name: "Papel de lija",
        price: 3.0,
        description: "Pack de 5 hojas grano 120",
        imageUrl: unsplashImg("sandpaper", 400, 300),
      },
      {
        category: "Pintura y acabados",
        name: "Masilla",
        price: 8.0,
        description: "Masilla de pared 1kg",
        imageUrl: unsplashImg("wall putty", 400, 300),
      },
      {
        category: "Pintura y acabados",
        name: "Barniz",
        price: 22.0,
        description: "Barniz brillante 1 litro",
        imageUrl: unsplashImg("varnish", 400, 300),
      },
      // Seguridad (3)
      {
        category: "Seguridad",
        name: "Casco de seguridad",
        price: 12.0,
        description: "Casco amarillo estándar",
        imageUrl: unsplashImg("safety helmet", 400, 300),
      },
      {
        category: "Seguridad",
        name: "Guantes de trabajo",
        price: 6.0,
        description: "Guantes de cuero",
        imageUrl: unsplashImg("work gloves leather", 400, 300),
      },
      {
        category: "Seguridad",
        name: "Gafas protectoras",
        price: 8.0,
        description: "Gafas transparentes",
        imageUrl: unsplashImg("safety glasses", 400, 300),
      },
      // Equipos (3)
      {
        category: "Equipos",
        name: "Taladro eléctrico",
        price: 45.0,
        description: "Taladro 500W con accesorios",
        imageUrl: unsplashImg("electric drill", 400, 300),
      },
      {
        category: "Equipos",
        name: "Sierra circular",
        price: 60.0,
        description: 'Sierra 7.25" 1200W',
        imageUrl: unsplashImg("circular saw", 400, 300),
      },
      {
        category: "Equipos",
        name: "Compresor de aire",
        price: 85.0,
        description: "Compresor 2HP 20 litros",
        imageUrl: unsplashImg("air compressor", 400, 300),
      },
    ],
    defaultModules: {
      inventory_tracking: true,
      coupons_discounts: true,
    },
  },
  {
    id: "pharmacy",
    archetype: "retail",
    label: "Farmacia",
    description: "Medicamentos, suplementos y productos de salud",
    categories: [
      { name: "Medicamentos", order: 1 },
      { name: "Suplementos", order: 2 },
      { name: "Productos de higiene", order: 3 },
      { name: "Primeros auxilios", order: 4 },
      { name: "Cuidado personal", order: 5 },
    ],
    products: [
      // Medicamentos (6)
      {
        category: "Medicamentos",
        name: "Paracetamol 500mg",
        price: 4.5,
        description: "Analgésico 20 comprimidos",
        imageUrl: unsplashImg("medicine tablet pills", 400, 300),
      },
      {
        category: "Medicamentos",
        name: "Ibuprofeno 400mg",
        price: 5.0,
        description: "Antiinflamatorio 15 cápsulas",
        imageUrl: unsplashImg("ibuprofen capsules", 400, 300),
      },
      {
        category: "Medicamentos",
        name: "Vitamina C",
        price: 8.0,
        description: "Vitamina C 1000mg 30 comprimidos",
        imageUrl: unsplashImg("vitamin c supplements", 400, 300),
      },
      {
        category: "Medicamentos",
        name: "Antihistamínico",
        price: 6.5,
        description: "Para alergias 10 comprimidos",
        imageUrl: unsplashImg("allergy medicine", 400, 300),
      },
      {
        category: "Medicamentos",
        name: "Jarabe para la tos",
        price: 7.0,
        description: "Jarabe 120ml",
        imageUrl: unsplashImg("cough syrup", 400, 300),
      },
      {
        category: "Medicamentos",
        name: "Probióticos",
        price: 12.0,
        description: "Probióticos 30 cápsulas",
        imageUrl: unsplashImg("probiotic supplement", 400, 300),
      },
      // Suplementos (6)
      {
        category: "Suplementos",
        name: "Multivitamínico",
        price: 15.0,
        description: "Complejo vitamínico 30 cápsulas",
        imageUrl: unsplashImg("multivitamin", 400, 300),
      },
      {
        category: "Suplementos",
        name: "Calcio + Vitamina D",
        price: 14.0,
        description: "Para huesos 60 comprimidos",
        imageUrl: unsplashImg("calcium vitamin d", 400, 300),
      },
      {
        category: "Suplementos",
        name: "Hierro",
        price: 10.0,
        description: "Suplemento de hierro 30 cápsulas",
        imageUrl: unsplashImg("iron supplement", 400, 300),
      },
      {
        category: "Suplementos",
        name: "Omega 3",
        price: 18.0,
        description: "Ácidos grasos 30 cápsulas",
        imageUrl: unsplashImg("omega 3 fish oil", 400, 300),
      },
      {
        category: "Suplementos",
        name: "Proteína en polvo",
        price: 22.0,
        description: "Proteína 500g",
        imageUrl: unsplashImg("protein powder", 400, 300),
      },
      {
        category: "Suplementos",
        name: "Melatonina",
        price: 11.0,
        description: "Para dormir 30 cápsulas",
        imageUrl: unsplashImg("melatonin sleep", 400, 300),
      },
      // Productos de higiene (6)
      {
        category: "Productos de higiene",
        name: "Jabón líquido",
        price: 3.5,
        description: "Jabón antibacterial 250ml",
        imageUrl: unsplashImg("liquid soap hand", 400, 300),
      },
      {
        category: "Productos de higiene",
        name: "Desinfectante",
        price: 4.0,
        description: "Desinfectante 500ml",
        imageUrl: unsplashImg("hand sanitizer", 400, 300),
      },
      {
        category: "Productos de higiene",
        name: "Pasta dental",
        price: 2.5,
        description: "Pasta dental 100ml",
        imageUrl: unsplashImg("toothpaste", 400, 300),
      },
      {
        category: "Productos de higiene",
        name: "Cepillo de dientes",
        price: 2.0,
        description: "Cepillo suave",
        imageUrl: unsplashImg("toothbrush", 400, 300),
      },
      {
        category: "Productos de higiene",
        name: "Enjuague bucal",
        price: 5.0,
        description: "Enjuague 500ml",
        imageUrl: unsplashImg("mouthwash", 400, 300),
      },
      {
        category: "Productos de higiene",
        name: "Hilo dental",
        price: 2.0,
        description: "Hilo dental 50m",
        imageUrl: unsplashImg("dental floss", 400, 300),
      },
      // Primeros auxilios (4)
      {
        category: "Primeros auxilios",
        name: "Venda elástica",
        price: 3.5,
        description: "Venda 5cm x 5m",
        imageUrl: unsplashImg("elastic bandage", 400, 300),
      },
      {
        category: "Primeros auxilios",
        name: "Curita adhesiva",
        price: 2.5,
        description: "Pack de 20 curitas",
        imageUrl: unsplashImg("band aid plaster", 400, 300),
      },
      {
        category: "Primeros auxilios",
        name: "Algodón estéril",
        price: 3.0,
        description: "Algodón 100g",
        imageUrl: unsplashImg("cotton wool", 400, 300),
      },
      {
        category: "Primeros auxilios",
        name: "Gasa estéril",
        price: 4.0,
        description: "Gasa 10cm x 10cm 10 piezas",
        imageUrl: unsplashImg("sterile gauze", 400, 300),
      },
      // Cuidado personal (2)
      {
        category: "Cuidado personal",
        name: "Crema facial",
        price: 12.0,
        description: "Hidratante facial 50ml",
        imageUrl: unsplashImg("face cream moisturizer", 400, 300),
      },
      {
        category: "Cuidado personal",
        name: "Protector solar",
        price: 9.0,
        description: "FPS 50 100ml",
        imageUrl: unsplashImg("sunscreen lotion", 400, 300),
      },
    ],
    defaultModules: {
      inventory_tracking: true,
      coupons_discounts: true,
    },
  },
  {
    id: "retail-en-blanco",
    archetype: "retail",
    label: "Retail en Blanco",
    description: "Template vacío para crear una tienda personalizada",
    categories: [{ name: "General", order: 1 }],
    products: [],
    defaultModules: getDefaultModulesForArchetype("retail"),
  },
];
