import { getDefaultModulesForArchetype } from "@foodorder/types";
import type { TemplateDefinition } from "./types";
import { unsplashImg } from "./image.helper";

export const SERVICE_TEMPLATES: TemplateDefinition[] = [
  {
    id: "plumbing-service",
    archetype: "service",
    label: "Plomería",
    description: "Servicios de plomería con presupuestos y cotizaciones",
    categories: [
      { name: "Reparaciones", order: 1 },
      { name: "Instalaciones", order: 2 },
      { name: "Mantenimiento", order: 3 },
      { name: "Emergencias", order: 4 },
    ],
    products: [
      // Reparaciones (4)
      {
        category: "Reparaciones",
        name: "Reparación de tuberías",
        price: 50.0,
        description: "Localización y reparación de fugas",
        imageUrl: unsplashImg("plumbing repair pipes", 400, 300),
      },
      {
        category: "Reparaciones",
        name: "Destape de desagüe",
        price: 35.0,
        description: "Desazolve profesional",
        imageUrl: unsplashImg("drain cleaning", 400, 300),
      },
      {
        category: "Reparaciones",
        name: "Reparación de llave de paso",
        price: 25.0,
        description: "Cambio o reparación de válvula",
        imageUrl: unsplashImg("water valve repair", 400, 300),
      },
      {
        category: "Reparaciones",
        name: "Reparación de grifo",
        price: 20.0,
        description: "Cambio de arandelas o grifería",
        imageUrl: unsplashImg("faucet repair", 400, 300),
      },
      // Instalaciones (4)
      {
        category: "Instalaciones",
        name: "Instalación de grifo",
        price: 40.0,
        description: "Grifo moderno de calidad",
        imageUrl: unsplashImg("faucet installation", 400, 300),
      },
      {
        category: "Instalaciones",
        name: "Instalación de sanitario",
        price: 80.0,
        description: "Instalación completa de inodoro",
        imageUrl: unsplashImg("toilet installation", 400, 300),
      },
      {
        category: "Instalaciones",
        name: "Instalación de ducha",
        price: 60.0,
        description: "Ducha con grifería",
        imageUrl: unsplashImg("shower installation", 400, 300),
      },
      {
        category: "Instalaciones",
        name: "Instalación de lavamanos",
        price: 45.0,
        description: "Lavamanos con caños",
        imageUrl: unsplashImg("sink installation bathroom", 400, 300),
      },
      // Mantenimiento (3)
      {
        category: "Mantenimiento",
        name: "Inspección anual",
        price: 60.0,
        description: "Revisión completa del sistema de plomería",
        imageUrl: unsplashImg("plumbing inspection", 400, 300),
      },
      {
        category: "Mantenimiento",
        name: "Limpieza de tuberías",
        price: 70.0,
        description: "Hidrojet y limpieza profunda",
        imageUrl: unsplashImg("pipe cleaning", 400, 300),
      },
      {
        category: "Mantenimiento",
        name: "Revisión de fugas",
        price: 40.0,
        description: "Detección de pérdidas de agua",
        imageUrl: unsplashImg("water leak detection", 400, 300),
      },
      // Emergencias (1)
      {
        category: "Emergencias",
        name: "Servicio de emergencia 24h",
        price: 100.0,
        description: "Atención prioritaria sin costo adicional",
        imageUrl: unsplashImg("emergency plumbing", 400, 300),
      },
    ],
    defaultModules: {
      quotes_estimates: true,
      labor_pricing: true,
      staff_management: true,
      payment_links: true,
      finance_documents: true,
    },
  },
  {
    id: "tech-support-service",
    archetype: "service",
    label: "Soporte Técnico IT",
    description: "Servicios de soporte técnico y mantenimiento de sistemas",
    categories: [
      { name: "Soporte", order: 1 },
      { name: "Instalación y configuración", order: 2 },
      { name: "Mantenimiento preventivo", order: 3 },
      { name: "Consultoría IT", order: 4 },
    ],
    products: [
      // type: 'service' para que ServiceFlowPage los muestre (filtra por labor|service)
      // Soporte (5)
      {
        category: "Soporte",
        name: "Soporte técnico remoto",
        price: 35.0,
        durationMin: 30,
        type: "service",
        description: "Asistencia por teléfono o escritorio remoto",
        imageUrl: unsplashImg("tech support remote", 400, 300),
      },
      {
        category: "Soporte",
        name: "Visita técnica",
        price: 60.0,
        durationMin: 60,
        type: "service",
        description: "Visita in-situ del técnico",
        imageUrl: unsplashImg("it technician", 400, 300),
      },
      {
        category: "Soporte",
        name: "Reparación de PC",
        price: 50.0,
        type: "service",
        description: "Diagnóstico y reparación",
        imageUrl: unsplashImg("computer repair", 400, 300),
      },
      {
        category: "Soporte",
        name: "Recuperación de datos",
        price: 100.0,
        type: "service",
        description: "Recuperación de información perdida",
        imageUrl: unsplashImg("data recovery", 400, 300),
      },
      {
        category: "Soporte",
        name: "Antivirus y seguridad",
        price: 45.0,
        type: "service",
        description: "Instalación y configuración de seguridad",
        imageUrl: unsplashImg("antivirus security", 400, 300),
      },
      // Instalación y configuración (4)
      {
        category: "Instalación y configuración",
        name: "Instalación de SO",
        price: 40.0,
        type: "service",
        description: "Instalación de Windows o Linux",
        imageUrl: unsplashImg("os installation", 400, 300),
      },
      {
        category: "Instalación y configuración",
        name: "Instalación de software",
        price: 30.0,
        type: "service",
        description: "Instalación y licenciamiento",
        imageUrl: unsplashImg("software installation", 400, 300),
      },
      {
        category: "Instalación y configuración",
        name: "Configuración de red",
        price: 70.0,
        type: "service",
        description: "Setup WiFi y LAN",
        imageUrl: unsplashImg("network setup", 400, 300),
      },
      {
        category: "Instalación y configuración",
        name: "Instalación de impresora",
        price: 25.0,
        type: "service",
        description: "Setup y drivers",
        imageUrl: unsplashImg("printer installation", 400, 300),
      },
      // Mantenimiento preventivo (3)
      {
        category: "Mantenimiento preventivo",
        name: "Limpieza y mantenimiento",
        price: 35.0,
        type: "service",
        description: "Limpieza interna y optimización",
        imageUrl: unsplashImg("computer maintenance", 400, 300),
      },
      {
        category: "Mantenimiento preventivo",
        name: "Actualización de software",
        price: 40.0,
        type: "service",
        description: "Parches y actualizaciones",
        imageUrl: unsplashImg("software update", 400, 300),
      },
      {
        category: "Mantenimiento preventivo",
        name: "Backup y sincronización",
        price: 50.0,
        type: "service",
        description: "Setup de respaldos automáticos",
        imageUrl: unsplashImg("backup cloud", 400, 300),
      },
      // Consultoría IT (2)
      {
        category: "Consultoría IT",
        name: "Consulta técnica",
        price: 75.0,
        durationMin: 60,
        type: "service",
        description: "Asesoramiento profesional",
        imageUrl: unsplashImg("it consultant", 400, 300),
      },
      {
        category: "Consultoría IT",
        name: "Análisis de seguridad",
        price: 100.0,
        type: "service",
        description: "Auditoría de sistemas",
        imageUrl: unsplashImg("security audit", 400, 300),
      },
    ],
    defaultModules: {
      quotes_estimates: true,
      labor_pricing: true,
      staff_management: true,
      payment_links: true,
      finance_documents: true,
    },
  },
  {
    id: "service-en-blanco",
    archetype: "service",
    label: "Servicios en Blanco",
    description:
      "Template vacío para crear un catálogo de servicios personalizado",
    categories: [{ name: "Servicios", order: 1 }],
    products: [],
    defaultModules: getDefaultModulesForArchetype("service"),
  },
];
